### ISSUE TITLE
Issue getting location from redirected request

### ISSUE THREAD

**Issue by mockfox** [sbstp/attohttpc#113]
I am trying to get the redirected location from a request that returns a 302 status code with a Location header. Using `response.headers().get("location")` returns `None`.

**Comment by adamreichold** [comment]
It might be necessary to push a complete example to figure out where the issue is.

The only thing I can think of ATM is that the default value of the `follow_redirects` setting is `true`, i.e. maybe your request did already following that redirection internally and your are inspecting the final response? You would need to set `follow_redirects` to `false` to be able to handle these yourself.

**Comment by mockfox** [comment]
Yes, it does follow the redirect internally. It did not make sense to me because res.status() returns `StatusCode::TEMPORARY_REDIRECT` or `StatusCode::PERMANENT_REDIRECT` while the headers have changed, but I can see why that is necessary. I will just have to make two request then. I was trying to avoid handling it this way (making two requests to track redirect locations).
