### ISSUE TITLE
Offer rustls as an alternative to native-tls

### ISSUE THREAD

**Issue by sbstp** [sbstp/attohttpc#48]
As suggested in the [smoke testing blog post](https://medium.com/@shnatsel/smoke-testing-rust-http-clients-b8f2ee5db4e6) we could offer to use the `rustls` TLS backend instead of `native-tls` with a feature flag.

**Comment by adamreichold** [comment]
Note that this seems to be non-trivial endeavor as the API provided by `rustls` is significantly more low level than `native-tls`, i.e. does not seem to provide a straight-forward implementation of `io::Read` and `io::Write`.

**Comment by sbstp** [comment]
Yeah what would be best is if there was a crate abstracting Tls functionality and allowed you to pick the backend.

**Comment by adamreichold** [comment]
@sbstp I have to correct myself: rustls already offers the [`StreamOwned`](https://docs.rs/rustls/0.16.0/rustls/struct.StreamOwned.html) wrapper to perform blocking I/O so that adding this [does not seem much more involved](https://github.com/adamreichold/zeptohttpc/commit/1973919750479b12be8e1f48d65c5e84953f30cf) than native-tls.

The need to handle the `ConnectionAborted` looks a bit strange but tokio-rustls uses the same condition to start its async shutdown dance.

If we want this to be even more high-level, we could use the rustls-connector crate but from the above linked commit I am not sure the additional dependency is worth the weight?
