### ISSUE TITLE
"missing or invalid location header" error on some websites

### ISSUE THREAD

**Issue by Shnatsel** [sbstp/attohttpc#93]
On some websites, e.g. http://futureuae.com, attohttpc fails with the following error:

> InvalidResponse: missing or invalid location header

Firefox and curl work fine.

96 websites out of the top million from [Feb 3 Tranco list](https://tranco-list.eu/list/3G6L) are affected.

Tested using [this code](https://github.com/Shnatsel/rust-http-clients-smoke-test/blob/main/attohttpc-smoke-test/src/main.rs). Test tool output from all affected websites: [atto-invalid-location-header.tar.gz](https://github.com/sbstp/attohttpc/files/5990781/atto-invalid-location-header.tar.gz)

**Comment by adamreichold** [comment]
The problem here is a relative redirect to the path
```
/ar-AE/Home/Index/2/\xd8\xa7\xd9\x84\xd8\xb1\xd8\xa6\xd9\x8a\xd8\xb3\xd9\x8a\xd8\xa9
```
which contains bytes which are not valid in an URL.

cURL seems to parse this into `/ar-AE/Home/Index/2/الرئيسية` and then requests
```
https://futureuae.com/ar-AE/Home/Index/2/%d8%a7%d9%84%d8%b1%d8%a6%d9%8a%d8%b3%d9%8a%d8%a9
```

#99 tries to fix this by using `String::from_utf8_lossy` which seems to end up with the same content as cURL, even though am I am not sure how the web server is configured to make this work...
